sudo: required
dist: trusty
language: node_js
node_js:
  - "stable"

install:
  - npm install --prefix ./src/front-src/
  - npm install --prefix ./src/back-src/
  - src/front-src/node_modules/protractor/bin/webdriver-manager update
script:
  - true

env:
  -  NODE_ENV=TEST NODE_PORT=3000 DB_SERVER_PORT=3306 MYSQL_TYPE=mysql MYSQL_HOST=localhost MYSQL_DATABASE=pgp_test MYSQL_USER=root MYSQL_PASSWORD=

before_deploy:
  - ls
  - cd ../
  - ls
  - zip -r release.zip back-src/ front-src/ -x "back-src/node_modules/*" "front-src/node_modules/*"
deploy:
  provider: releases
  api_key: "da9183a769d7d5964d49b60dd18ff3ef68d3c182"
  on:
    tags: true
  file: release.zip
