FROM nginx:1.13

# install npm
# copy configuration files
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf

#RUN ls -la /usr/share/nginx/html/
RUN rm /usr/share/nginx/html/index.html

#RUN ls -la /etc/nginx
#RUN ls -la /etc/nginx/conf.d
#RUN cat /etc/nginx/nginx.conf

# copy server files
COPY ./index.html /usr/share/nginx/html/

# copy and build application
RUN ls -la /root
RUN mkdir /root/app
WORKDIR /root/app
COPY ./wait-for-it.sh /root/app/

#COPY ./.angular-cli.json /root/app/
#COPY ./package.json /root/app/
#COPY ./package-lock.json /root/app/
COPY . /root/app/

RUN npm install
RUN npm build

RUN cp -r /root/app/dist/ /usr/share/nginx/html/

CMD ["./wait-for-it.sh", "backend:3000", "-t", "30", "--", "nginx", "-g", "daemon off;"]

